plugins = []
headers = []
redirects = []

[functions]
directory = "functions"

  [functions."*"]

[build]
publish = "C:\\Users\\derus\\OneDrive\\Documentos\\Sharly Mantilla\\prueba 1\\MARA"
publishOrigin = "default"

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]
